apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/fabremartin/gitops
  ref:
    branch: main
  secretRef:
    name: fluxcd-key
