name: flux-workflow

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'mickey'
          required: true
          default: 'prd'

jobs:
  configure-flux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Flux CLI
        uses: fluxcd/flux2/action@main
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Azure environment variables
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CREDENTIALS.clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CREDENTIALS.clientSecret }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_CREDENTIALS.tenantId }}" >> $GITHUB_ENV

      # Étape 3: Authentification à Azure
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
      - name: Setup Kubernetes Config
        run: |
            az aks get-credentials --resource-group rg-1 --name cluster-aks --file kubeconfig.yaml
            echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Configure Flux with Git Repository
        run: |
          # Check if Flux controllers are ready
          kubectl -n flux-system wait --for=condition=available --timeout=180s deployment/source-controller deployment/kustomize-controller
          
          # Create or update the GitRepository
          flux create source git flux-repo \
            --url=${{ secrets.GIT_REPOSITORY_URL }} \
            --branch=main \
            --secret-ref=fluxcd-key \
            --namespace=flux-system \
            --export > git-repository.yaml
            
          kubectl apply -f git-repository.yaml
          
          # Create the Kustomization
          flux create kustomization kustomization \
            --source=flux-repo \
            --path="." \
            --prune=true \
            --interval=10m \
            --target-namespace=default \
            --namespace=flux-system \
            --export > kustomization.yaml
            
          kubectl apply -f kustomization.yaml
          
          echo "FluxCD has been configured successfully!"
