name: flux-workflow

on:
    workflow_dispatch:
env:
  ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
  ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  ARM_USE_CLI: false

jobs:
  configure-flux:
    runs-on: ubuntu-latest
    steps:
      # Step 1: source code checkout
      - name: Checkout
        uses: actions/checkout@v3
      
      # Step 2: Flux setup
      - name: Install Flux CLI
        uses: fluxcd/flux2/action@main
        
      # Step 3: Kube setup
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # Step 5: Azure login
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
      # Step 6: Kube config
      - name: Setup Kubernetes Config
        run: |
            az aks get-credentials --resource-group rg-1 --name cluster-aks --file kubeconfig.yaml
            echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      # Step 7: GitOps Configuration (Kustomize and GitRepo)
      - name: Configure GitOps
        run: |
            # Check if Flux controllers are ready
            kubectl -n flux-system wait --for=condition=available --timeout=180s deployment/source-controller deployment/kustomize-controller
          
            # Apply GitRepository and Kustomization directly from your repo's files
            kubectl apply -f ./gitops/git-repository.yaml
            kubectl apply -f ./gitops/kustomization.yaml
          
            echo "FluxCD & Gitops have been configured successfully!"

      - name: Create ACR secret for Flux
        run: |
          echo "Creating Docker Registry secret..."
          kubectl create secret docker-registry flux-azure-registry \
          --docker-server=regsitry14032025.azurecr.io \
          --docker-username="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
          --docker-password="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
          --namespace=default \
          --dry-run=client -o yaml | kubectl apply -f -
          