name: infra-workflow

on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: source code checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Terraform setup
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      # Step 3: Azure env setup
      - name: Set up Azure environment variables
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CREDENTIALS.clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CREDENTIALS.clientSecret }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_CREDENTIALS.tenantId }}" >> $GITHUB_ENV

      # Step 4: Azure login
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      # Step 5: Terraform init
      - name: Terraform Init
        run: terraform init -upgrade

      # Step 6: Terraform plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        id: plan
        env:
          TF_VAR_fluxcd_key: ${{ secrets.FLUXCD_KEY }}
          TF_VAR_fluxcd_key_pub: ${{ secrets.FLUXCD_KEY_PUB }}
          TF_VAR_known_hosts: ${{ secrets.KNOWN_HOSTS }}
          KUBECONFIG: ${{ env.KUBECONFIG }}

      # Step 7: Terraform apply
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        env:
            TF_VAR_fluxcd_key: ${{ secrets.FLUXCD_KEY }}
            TF_VAR_fluxcd_key_pub: ${{ secrets.FLUXCD_KEY_PUB }}
            TF_VAR_known_hosts: ${{ secrets.KNOWN_HOSTS }}
            KUBECONFIG: ${{ env.KUBECONFIG }}

  

